    spring:
      security:
        oauth2:
          client:
            registration:
              google:
                client-id: 382001242979-fncvcgdq85306eqp3oc0lhrgtna6p504.apps.goolgleusercontent.com
                  client-secret:GOCSPX-AVcaekUozd_2npyDJ1K1lxRAtsR


